import { generateUniqueId } from './pricing.js';

// Session state stays private to this module graph; persisted records remain UID/shop scoped.
export const state = {
  currentCustomer: {},
  currentDeliveryDate: '',
  giftCart: [],
  cakeCart: [],
  giftboxCart: [],
  allProducts: [],
  currentModalProduct: null,
  confirmCallback: null,
  isCompanyCustomer: false,
  isSubmittingOrder: false,
  currentGiftboxSize: 0,
  giftboxSelection: {},
  currentGiftboxCombo: null,
  editingGiftboxIndex: -1,
  isEditingOrder: false,
  editingOrderId: null,
  expandedSearchOrderId: null,
  collapsingSearchOrderId: null,
  orderItemsTransitionTimer: null,
  currentSearchOrders: [],
  currentOrderTableType: null,
  currentContactMethod: 'phone',
  currentSearchContactMethod: 'phone',
  searchNextCursor: null,
  lastSearchCriteria: null,
  isLoadingMoreOrders: false,
  draftSaveTimer: null,
  restoredDraftKey: null,
  suppressDraftSave: false,
  posLocalDbPromise: null,
  currentOrderRequestId:
    typeof crypto.randomUUID === 'function' ? crypto.randomUUID() : generateUniqueId('REQ'),
  viewportProbeObserver: null,
  viewportRemeasureTimer: null,
  acDebounceTimer: null,
  acResultsCache: [],
  customerSearchCache: new Map(),
  currentProductFilter: '全部',
  searchDatepickerInstance: null,
  reportDatepickerInstance: null,
  buttonClickStates: new Set(),
  currentStatusOrderId: null,
  currentStatusValue: null,
  statusSliderCtrl: null,
  deleteSliderCtrl: null,
  calendarState: {
    currDate: new Date(),
    currYear: new Date().getFullYear(),
    currMonth: new Date().getMonth(),
    selectedDateStr: null,
  },
  monthNames: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
  demandDateLocaleZh: {
    days: ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六'],
    daysShort: ['週日', '週一', '週二', '週三', '週四', '週五', '週六'],
    daysMin: ['日', '一', '二', '三', '四', '五', '六'],
    months: [
      '一月',
      '二月',
      '三月',
      '四月',
      '五月',
      '六月',
      '七月',
      '八月',
      '九月',
      '十月',
      '十一月',
      '十二月',
    ],
    monthsShort: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
    today: '今天',
    clear: '清除',
    dateFormat: 'yyyy-MM-dd',
    timeFormat: 'HH:mm',
    firstDay: 0,
  },
  overrideDatepickerInstance: null,
  demandDatepickerInstance: null,
  weekdayNames: ['日', '一', '二', '三', '四', '五', '六'],
  capacitySettings: { weekday: {}, dateOverrides: [] },
  capacitySettingsLoaded: false,
  monthCapacityCache: {},
  pendingOrderData: null,
  _weekdayCapacityDebounceTimer: null,
  capacityInflight: {},
  orderSubmitWatchdog: null,
  deleteOrderId: null,
  currentDepositOrderId: null,
  currentDepositTotalAmount: 0,
  currentDepositAmount: 0,
};
